[aptly]
patchops-aptly ansible_host=localhost ansible_port=2200 ansible_user=aptly

[govdb]
patchops-govdb ansible_host=patchops-govdb ansible_port=5432 ansible_user=postgres

[dev]
ansible-ubuntu1 ansible_port=2201 aptly_env=dev
ansible-ubuntu2 ansible_port=2202 aptly_env=dev

[staging]
ansible-ubuntu3 ansible_port=2203 aptly_env=staging

[prod]
ansible-ubuntu4 ansible_port=2204 aptly_env=prod
ansible-ubuntu5 ansible_port=2205 aptly_env=prod

[ubuntu:children]
dev
staging
prod

[all:vars]
ansible_host=localhost
ansible_python_interpreter=/usr/bin/python3
ansible_connection=ssh
