[ubuntu]
ansible-ubuntu1 ansible_port=2201
ansible-ubuntu2 ansible_port=2202
ansible-ubuntu3 ansible_port=2203
ansible-ubuntu4 ansible_port=2204
ansible-ubuntu5 ansible_port=2205

[all:vars]
ansible_host=localhost
ansible_python_interpreter=/usr/bin/python3
