apiVersion: 1

datasources:
  - name: patchgov
    type: postgres
    uid: patchgov
    access: proxy
    url: patchops-govdb:5432
    database: patchgov
    user: postgres
    secureJsonData:
      password: "$__env{GOVDB_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
